# Generated by Django 4.2.26 on 2025-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_alter_todo_options_category_todo_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["completed_at", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
