# Generated by Django 4.2.26 on 2025-11-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0006_todo_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
