# Generated by Django 4.2.26 on 2025-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0008_alter_todo_options_todo_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="effort",
            field=models.IntegerField(default=0, help_text="Effort level from 0 to 10"),
        ),
    ]
