# Generated by Django 4.2.26 on 2025-11-20 01:39

from django.db import migrations


def create_modify_todos_permission(apps, schema_editor):
    """
    Create custom permission 'can_modify_todos' on the User model.
    This permission allows users to create, edit, and delete todos and categories.
    Users without this permission have read-only access (demo mode).
    """
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    User = apps.get_model("auth", "User")

    # Get or create the ContentType for User model
    content_type, _ = ContentType.objects.get_or_create(app_label="auth", model="user")

    # Create the permission
    permission, created = Permission.objects.get_or_create(
        codename="can_modify_todos",
        content_type=content_type,
        defaults={"name": "Can modify todos and categories"},
    )

    if created:
        # Grant this permission to all existing users (except those we'll mark as demo later)
        # This ensures existing users maintain their current access
        for user in User.objects.all():
            user.user_permissions.add(permission)


def remove_modify_todos_permission(apps, schema_editor):
    """Reverse migration: remove the custom permission."""
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    try:
        content_type = ContentType.objects.get(app_label="auth", model="user")
        Permission.objects.filter(
            codename="can_modify_todos", content_type=content_type
        ).delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0009_todo_effort"),
        ("auth", "__latest__"),
        ("contenttypes", "__latest__"),
    ]

    operations = [
        migrations.RunPython(
            create_modify_todos_permission, remove_modify_todos_permission
        ),
    ]
